from types import SimpleNamespace

from ._adaptors import (Concat, Counted, Drop, DropWhile, Elements, Enumerate,
                        Filter, Join, JoinWith, Keys, Reverse, Split, Take,
                        TakeWhile, To, Transform, Values)
from ._core import Range, RangeAdaptor, RangeGenerator
from ._generators import Empty, Indices, Iota, Repeat, Single


Ranges: SimpleNamespace = SimpleNamespace(
    Range=Range,
    RangeAdaptor=RangeAdaptor,
    RangeGenerator=RangeGenerator,
    To=To,
    Counted=Counted,
    Elements=Elements,
    Keys=Keys,
    Values=Values,
    Enumerate=Enumerate,
    Concat=Concat,
    Reverse=Reverse(),
    Filter=Filter,
    Take=Take,
    Drop=Drop,
    DropWhile=DropWhile,
    Join=Join,
    JoinWith=JoinWith,
    Split=Split,
    TakeWhile=TakeWhile,
    Single=Single,
    Empty=Empty,
    Iota=Iota,
    Indices=Indices,
    Repeat=Repeat,
    Transform=Transform,
)

__all__ = [
    "Drop",
    "DropWhile",
    "Counted",
    "Elements",
    "Enumerate",
    "Empty",
    "Filter",
    "Indices",
    "Iota",
    "Join",
    "JoinWith",
    "Keys",
    "Range",
    "RangeAdaptor",
    "RangeGenerator",
    "Ranges",
    "Repeat",
    "Reverse",
    "Single",
    "Split",
    "Take",
    "TakeWhile",
    "To",
    "Transform",
    "Values",
    "Concat",
]
