from types import SimpleNamespace

from ._adaptors import (Adjacent, AdjacentTransform, CartesianProduct, Chunk,
                        ChunkBy, Concat, Counted, Drop, DropWhile, Elements,
                        Enumerate, Filter, Join, JoinWith, Keys, Pairwise,
                        PairwiseTransform, Reverse, Slide, Split, Stride,
                        SupportsGetItem, Take, TakeWhile, To, Transform, Values,
                        Zip, ZipTransform)
from ._core import Range, RangeAdaptor, RangeGenerator
from ._generators import Empty, Indices, Iota, Repeat, Single
from . import ranges, views


Ranges: SimpleNamespace = SimpleNamespace(
    Range=Range,
    RangeAdaptor=RangeAdaptor,
    RangeGenerator=RangeGenerator,
    To=To,
    Counted=Counted,
    Elements=Elements,
    SupportsGetItem=SupportsGetItem,
    Keys=Keys,
    Values=Values,
    Enumerate=Enumerate,
    Concat=Concat,
    Zip=Zip,
    ZipTransform=ZipTransform,
    Adjacent=Adjacent,
    Pairwise=Pairwise,
    AdjacentTransform=AdjacentTransform,
    PairwiseTransform=PairwiseTransform,
    Chunk=Chunk,
    Slide=Slide,
    ChunkBy=ChunkBy,
    Stride=Stride,
    CartesianProduct=CartesianProduct,
    Reverse=Reverse(),
    Filter=Filter,
    Take=Take,
    Drop=Drop,
    DropWhile=DropWhile,
    Join=Join,
    JoinWith=JoinWith,
    Split=Split,
    TakeWhile=TakeWhile,
    Single=Single,
    Empty=Empty,
    Iota=Iota,
    Indices=Indices,
    Repeat=Repeat,
    Transform=Transform,
)

__all__ = [
    "Drop",
    "DropWhile",
    "Counted",
    "Elements",
    "Enumerate",
    "Empty",
    "Filter",
    "Indices",
    "Iota",
    "Join",
    "JoinWith",
    "Keys",
    "Range",
    "RangeAdaptor",
    "RangeGenerator",
    "Ranges",
    "Repeat",
    "Reverse",
    "Single",
    "Split",
    "Take",
    "TakeWhile",
    "To",
    "Transform",
    "Values",
    "Concat",
    "Zip",
    "ZipTransform",
    "Adjacent",
    "Pairwise",
    "AdjacentTransform",
    "PairwiseTransform",
    "Chunk",
    "Slide",
    "ChunkBy",
    "Stride",
    "CartesianProduct",
    "SupportsGetItem",
    "ranges",
    "views",
]
